#!/usr/bin/env python3
#
# Generate pygl.pyi from the built module. Every wrapper carries a docstring
# whose first line is its call signature (e.g. "ClearColor(red, green, blue,
# alpha)"), which is enough for editors to show argument names.
#
#   python3 tools/stubgen.py > pygl.pyi
#

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import pygl

SIG = re.compile(r'^([A-Za-z_]\w*)\((.*?)\)\s*(?:->\s*(.+))?$')

HEADER = '''\
# Generated by tools/stubgen.py - do not edit by hand.
# Argument names come from the OpenGL registry / wrapper docstrings; the
# bindings accept ints and floats interchangeably for numeric parameters.
from typing import Any

'''


def main():
    lines = [HEADER]

    consts = sorted(n for n in dir(pygl)
                    if not n.startswith('_') and isinstance(getattr(pygl, n), int))
    for name in consts:
        lines.append('%s: int' % name)
    lines.append('')

    funcs = sorted(n for n in dir(pygl)
                   if not n.startswith('_') and callable(getattr(pygl, n)))
    for name in funcs:
        doc = (getattr(pygl, name).__doc__ or '').strip().splitlines()
        params, ret = '*args: Any', 'Any'
        if doc:
            m = SIG.match(doc[0].strip())
            if m and m.group(1) == name:
                raw = [p.strip() for p in m.group(2).split(',') if p.strip()]
                fixed = []
                for p in raw:
                    key, _, default = p.partition('=')
                    key = key.strip()
                    fixed.append('%s: Any = ...' % key if default else '%s: Any' % key)
                params = ', '.join(fixed)
                if m.group(3):
                    ret = 'Any'
        lines.append('def %s(%s) -> %s: ...' % (name, params, ret))

    sys.stdout.write('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
